remote_theme: beAuthentic/askclass-news-theme
#theme: askclass-news-theme

title: Milpitas Christian Church
description: >
  Proclaiming the unsearchable riches of Christ.
acn:
  date_format: "%b %d, %Y"
  short_name: MCC
  color:
    theme: "#fec601"
    bg: "#263238"
  url: "https://milpitas.cc"
  categories:
    - education
    - kids
    - music
    - books
  social:
    twitter: "thienky"
  logo:
    image: "logo.svg"
    size: 70
    alt_image: "logo.svg"
    alt_size: 70
    sizes: [ 48, 96, 144, 192, 300, 512, 800, 1024 ]
  meta:
    apple_icon: "logo-512.png"
    og_image: "logo-square-1024.png"
    shortcut:
      favicon: "favicon.ico"
      type: "image/png"
      image: "logo-96.png"
    keywords: >
      God,
      Christian,
      Christ,
      Holy Spirit,
      Trinity,
      church,
      education,
      learning
  footer:
    - icon: "arrow_right"
      href: "https://nissi.church"
      text: "Nissi Church"
    - icon: "arrow_right"
      href: "https://nissi.church/awana"
      text: "Awana"
  font_families:
    - Teko
    - Open+Sans
    - Josefin+Sans
    - Share+Tech+Mono
    - Material+Icons

collections_dir: content
collections:
  writers:
    output: true
  hashtags:
    output: true

ignore_theme_config: false
excerpt_separator: "<!--more-->"
permalink: /:year/:month/:day/:title

defaults:
  - scope:
      type: "hashtags"
    values:
      layout: "hashtag"
  - scope:
      type: "writers"
    values:
      layout: "writer"
  - scope:
      type: "posts"
    values:
      layout: "post"

exclude:
  - CNAME
  - runme.sh
